name: Build and Test

on:
  push:
    branches: [ master, vadim/action-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Actions checkout
      uses: actions/checkout@v2   
    - uses: ./.github/actions/test
      with:
        project_path: LinqArray/Vim.LinqArray.csproj
        package_name: Vim.LinqArray
