name: Build and Test

on:
  push:
    branches: [ master, vadim/action-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: vimaec/ci-cd-scripts
        ref: refs/heads/vadim/test
        path: .github/
    - uses: ./.github/actions/build-and-test
      with:
        project_path: LinqArray/Vim.LinqArray.csproj
        root_path: ".github"
