name: Test

on:
  push:
    branches: [ vadim/action-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: vimaec/ci-cd-scripts
        ref: refs/heads/vadim/test
        path: .github/
    - uses: ./.github/actions/test
